### ISSUE TITLE
VUnit Support

### ISSUE THREAD

**Issue by mattdominik** [sigasi/SigasiProjectCreator#24]
Please can you add VUnit Support to the SigasiProjectCreator

**Comment by bartbrosens** [comment]
Hi @mattdominik,

Thank you for your suggestion.

The instructions on (manually) setting up a VUnit project in Sigasi Studio are available [in our manual](https://insights.sigasi.com/manual/vunit/). Can you elaborate on how you would specify whether the ProjectCreator scripts should add VUnit support to a Sigasi project?

To add VUnit support to a project, the output generated by the ProjectCreator scripts should contain:
* a reference to the VUnit builder in the `.project` file
* a reference to the VUnit nature in the `.project` file
* a file `.settings/com.sigasi.hdt.toolchains.vunit.prefs` containing the location of the `run.py` script

**Comment by mattdominik** [comment]
Hi @bartbrosens,

It would be nice to have functions for adding Builder and Nature in the .project file

**Comment by mattdominik** [comment]
Are there any updates?

**Comment by bartbrosens** [comment]
Hi @mattdominik,

This hasn't been a top priority so far. I plan adding an example for the VUnit support next week. Meanwhile we'll take PR's on this.

**Comment by bartbrosens** [comment]
Hi @mattdominik,

I've started a PR with VUnit support added by default using any of the `convertCsvFileToLinks.py` and `convertCsvFileToTree.py` files. Is this usable for you?
