### ISSUE TITLE
Improve command line options for example functions

### ISSUE THREAD

**Issue by bartbrosens** [sigasi/SigasiProjectCreator#26]
Remaining issue from #25 :

* add command line option(s) for `convertCsvFileToLinks.py` and `convertCsvFileToTree.py` to make VUnit configuration optional

**Comment by bartbrosens** [comment]
Using [argparse](https://docs.python.org/3/library/argparse.html) would improve the command line option handling.

**Comment by wmeeus** [comment]
Obsolete with #23
