### ISSUE TITLE
Tests fail due to hardcoded path

### ISSUE THREAD

**Issue by nitzsche-fzi** [sigasi/SigasiProjectCreator#46]
Minor bug, but I thought I would report it anyway:

The python tests fail during `test_parse_and_create_project()` in `tests/ProjectCreatorTest.py`, probably due to a hardcoded path in line 444:
`/home/wmeeus/git/SigasiProjectCreator_github/uvm/src`

**Comment by wmeeus** [comment]
@nitzsche-fzi thanks for reporting. A fix is on its way as part of https://github.com/sigasi/SigasiProjectCreator/pull/43/files
